// src/components/HeroSection.tsx
import { profile } from '../data';

export default function HeroSection() {
  return (
    <section
      id="about"
      className="border-b border-slate-800 bg-gradient-to-b from-slate-900/60 to-slate-950 py-20"
      aria-labelledby="about-heading"
    >
      <div className="mx-auto flex max-w-6xl flex-col gap-10 px-6 md:flex-row md:items-center">
        <div className="space-y-5 md:w-2/3">
          <h1 id="about-heading" className="text-4xl font-semibold leading-tight sm:text-5xl">
              {profile.name}
          </h1>
            <p className="text-lg text-slate-200">{profile.title}</p>
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-300">About</p>
          <p className="text-base leading-7 text-slate-300">{profile.about}</p>
          <div className="flex flex-wrap gap-2 text-sm text-indigo-300">
            <span className="rounded-full border border-indigo-500/40 px-3 py-1">{profile.location}</span>
            <span className="rounded-full border border-indigo-500/40 px-3 py-1">Open to internships</span>
          </div>
        </div>
        <div className="flex flex-1 justify-center">
          <div className="relative h-56 w-56 overflow-hidden rounded-3xl border border-slate-800 bg-slate-900/80 shadow-2xl shadow-indigo-900/40">
            <img src={profile.photo} alt={profile.name} className="h-full w-full object-cover" loading="lazy" />
          </div>
        </div>
      </div>
    </section>
  );
}

// frontend/src/components/sections/HeroSection.vue
<template>
  <section class="border-b border-slate-800 bg-gradient-to-b from-slate-900/60 to-slate-950 py-20">
    <div class="mx-auto flex max-w-5xl flex-col gap-10 px-6 md:flex-row md:items-center">
      <div class="space-y-6 md:w-2/3">
        <p class="text-sm uppercase tracking-[0.3em] text-indigo-300">Product Designer · Frontend Engineer</p>
        <h1 class="text-4xl font-semibold leading-tight sm:text-5xl">Designing inclusive, resilient digital products.</h1>
        <p class="text-lg text-slate-300">
          I partner with founders and product teams to translate complex problems into human-centered experiences,
          balancing insight, craft, and technical fluency.
        </p>
        <div class="flex flex-wrap gap-3">
          <a
            href="#projects"
            class="rounded-full bg-indigo-500 px-5 py-3 text-sm font-semibold uppercase tracking-[0.3em] text-slate-50 shadow-lg shadow-indigo-500/40"
          >
            View selected work
          </a>
          <a
            href="#contact"
            class="rounded-full border border-slate-700 px-5 py-3 text-sm font-semibold uppercase tracking-[0.3em] text-slate-200"
          >
            Let's collaborate
          </a>
        </div>
      </div>
      <div class="flex-1 rounded-3xl border border-slate-800 bg-slate-900/60 p-10 text-sm leading-7 text-slate-300 shadow-xl">
        <p class="font-semibold uppercase tracking-[0.3em] text-indigo-300">Highlights</p>
        <ul class="mt-6 space-y-4">
          <li><strong class="text-white">8+ years</strong> supporting high-growth product teams</li>
          <li><strong class="text-white">Design systems</strong> that scale with velocity</li>
          <li><strong class="text-white">Accessibility</strong> woven into discovery, delivery, and QA</li>
        </ul>
      </div>
    </div>
  </section>
</template>
